export const hobbies = [
  "Reading",
  "Writing",
  "Painting",
  "Drawing",
  "Photography",
  "Cooking",
  "Baking",
  "Gardening",
  "Yoga",
  "Meditation",
  "Hiking",
  "Running",
  "Swimming",
  "Biking",
  "Rock climbing",
  "Surfing",
  "Skiing/snowboarding",
  "Fishing",
  "Hunting",
  "Camping",
  "Birdwatching",
  "Stargazing",
  "Geocaching",
  "Sculpting",
  "Knitting",
  "Crocheting",
  "Sewing",
  "Embroidery",
  "Quilting",
  "Scrapbooking",
  "Collaging",
  "Woodworking",
  "Metalworking",
  "Glassblowing",
  "Pottery",
  "Blacksmithing",
  "Jewelry making",
  "Calligraphy",
  "Graffiti art",
  "Breakdancing",
  "DJing",
  "Music production",
  "Singing",
  "Playing a musical instrument",
  "Acting",
  "Stand-up comedy",
  "Improv",
  "Magic tricks",
  "Circus skills",
  "Escape rooms",
];

export const festivals = [
  "New Year's Day (celebrated on January 1)",
  "Valentine's Day (celebrated on February 14)",
  "Easter (celebrated in March or April)",
  "International Workers' Day (celebrated on May 1)",
  "Halloween (celebrated on October 31)",
  "Diwali (celebrated in October or November)",
  "Thanksgiving (celebrated on the fourth Thursday in November in the United States)",
  "Hanukkah (celebrated in December)",
  "Christmas (celebrated on December 25)",
  "Kwanzaa (celebrated from December 26 to January 1)",
  "Lunar New Year (celebrated on the first day of the first month of the lunar calendar)",
  "Carnival (celebrated in the weeks leading up to Ash Wednesday)",
  "Mardi Gras (celebrated on the Tuesday before Ash Wednesday)",
  "St. Patrick's Day (celebrated on March 17)",
  "International Women's Day (celebrated on March 8)",
  "Children's Day (celebrated on various dates around the world)",
  "International Day of Peace (celebrated on September 21)",
  "International Day of the Girl Child (celebrated on October 11)",
  "International Day of the Older Person (celebrated on October 1)",
  "International Day of the Forest (celebrated on March 21)",
  "International Day of the Sea (celebrated on April 14)",
  "International Day of the Youth (celebrated on August 12)",
  "International Day of the Disabled Person (celebrated on December 3)",
  "International Day of the Child (celebrated on November 20)",
  "International Day of Families (celebrated on May 15)",
  "International Day of the Environment (celebrated on June 5)",
  "International Day of the AIDS Candlelight Memorial (celebrated on May 16)",
  "International Day of the Youth (celebrated on August 12)",
  "International Day of the Girl Child (celebrated on October 11)",
  "International Day of the Older Person (celebrated on October 1)",
  "International Day of the Forest (celebrated on March 21)",
  "International Day of the Sea (celebrated on April 14)",
  "International Day of the Youth (celebrated on August 12)",
  "International Day of the Disabled Person (celebrated on December 3)",
  "International Day of the Child (celebrated on November 20)",
  "International Day of Families (celebrated on May 15)",
  "International Day of the Environment (celebrated on June 5)",
  "International Day of the AIDS Candlelight Memorial (celebrated on May 16)",
  "International Day of Peace (celebrated on September 21)",
  "International Day of the Girl Child (celebrated on October 11)",
  "International Day of the Older Person (celebrated on October 1)",
  "International Day of the Forest (celebrated on March 21)",
  "International Day of the Sea (celebrated on April 14)",
  "International Day of the Youth (celebrated on August 12)",
  "International Day of the Disabled Person (celebrated on December 3)",
  "International Day of the Child (celebrated on November 20)",
];
